version: '3.5'
services:

  devzone-db:
    image: postgres:12.3
    container_name: devzone-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  devzone-api-golang:
    build: .
    ports:
      - "18080:8080"
    restart: unless-stopped
    depends_on:
      - devzone-db
    environment:
      APP_DB_HOST: devzone-db
      APP_DB_PORT: 5432
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_NAME: postgres
      APP_DB_RUN_MIGRATIONS: "true"